name: env_co2_emissions_rwanda_kaggle 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab=4.0
  - numpy=1.25
  - matplotlib=3.7
  - pandas=2.0
  - seaborn
  - scikit-learn=1.3
  - statsmodels
  - pip
  - pip:
    -  jupyterlab-vim == 4.0.2 
